### ISSUE TITLE
rspec does not run because spec/spec_helper.rb is missing a line of code

### ISSUE THREAD

**Issue by jin501** [learn-co-curriculum/basic-sinatra-forms-lab#11]
spec/spec_helper needs to require 'capybara/rspec' in order to run rspec

**Comment by zoebisch** [comment]
I was having an issue where even after bundling, and trying to run rspec, got: "spec_helper.rb:4:in `require': cannot load such file -- capybara/poltergeist (LoadError)"

So I added your comment, (capybara/rspec) and commented out the require 'capybara/poltergeist' line.  This allowed me to run rspec and get through the lab.

**Comment by sgharms** [comment]
You both were on the right track. We're doing it a little differently, but this idea is getting integrated into `master`.
