### ISSUE TITLE
Solution seems off

### ISSUE THREAD

**Issue by howardbdev** [learn-co-curriculum/basic-sinatra-forms-lab#13]
In the solution file, app.rb seems funny:
There is never a call to `erb :team` so the `team.erb` file is never in play
The instance variables are from the previous lesson and in the wrong place, and there is leftover code from previous lesson where we reversed a string using a form.
Here is what I think it sould look like:

require 'sinatra/base'

class App < Sinatra::Base

  get '/newteam' do
    erb :newteam
  end

  post '/team' do
    @name = params["name"]
    @coach = params["coach"]
    @pg = params["pg"]
    @sg = params["sg"]
    @sf = params["sf"]
    @pf = params["pf"]
    @c = params["c"]
    erb :team
  end

end

**Comment by sgharms** [comment]
@howardbdev 

I'm looking at this much later, but as this point the README says that the `team.erb` is to be used as part of the POST to `/team`. It seems like previous code has been removed, etc. I think things are fixed. If not, let me know.
