### ISSUE TITLE
the submit button needs an ID, which is non-obvious

### ISSUE THREAD

**Issue by williamhancharek** [learn-co-curriculum/basic-sinatra-forms-lab#17]
Hi,

From previous lessons, it was not apparent that capybara's test suite needs to have the submit button have an id of "submit"

<form method="post" action="/team">
     <p>Team name: <input type="text" name="name"></p>
     <p>Coach: <input type="text" name="coach"></p>
     <p>Point guard: <input type="text" name="pg"></p>
     <p>Shooting Guard: <input type="text" name="sg"></p>
     <p>Power Forward: <input type="text" name="pf"></p>
     <p>Small Forward: <input type="text" name="sf"></p>
     <p>Center: <input type="text" name="c"></p>
     <input type="submit" name="submit" id="submit">

The above works, but it also works with:
     <input type="submit">

which is confusing since the app works and does what is expected, but the tests don't pass..?

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue.

Sincerely,

Flatiron Curriculum Team
