### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by travislavery** [learn-co-curriculum/basic-sinatra-forms-lab#21]
In your instructions for this lab, it says that capybara is looking for a name or id of "Submit". In the tests however, it is looking for a name of label of "submit". Lower case s. If it is uppercase, as in the instructions, the test will fail. I recommend changing the instructions or test to reflect each other.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
