### ISSUE TITLE
id/name attribute for submit button

### ISSUE THREAD

**Issue by NolanHughes** [learn-co-curriculum/basic-sinatra-forms-lab#23]
There is a paragraph in the instructions of this lab that states, "When creating your form, your "Submit" button will need to be identified by either an id attribute or a name attribute with value of "Submit"." I have found two issues with this instruction. For both of the issues below I receive the same error. 

`Capybara::ElementNotFound: Unable to find visible button "submit"`

1. The value has to be "submit" not "Submit" to get the tests to pass.
2. Secondly, setting an attribute as name and it's value as "submit" brings about the error above as well. I could be setting the name attribute incorrectly, but I don't think so since I followed how we previously did it in labs and looked at W3 school for clarification on attributes for input and button tags. When I changed the attribute to either 'id' or 'value' all of the tests pass.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
