### ISSUE TITLE
Incorrect statement - should be "both" instead of "either"

### ISSUE THREAD

**Issue by alexcrisan** [learn-co-curriculum/basic-sinatra-forms-lab#24]
"When creating your form, your "Submit" button will need to be identified by
either an id attribute or a name attribute with value of "Submit"." 

This statement is misleading. It says that the form should have EITHER an id attribute OR a name attribute with the value of "submit", but the only way to make the tests pass is if BOTH the type AND the id are set to "submit". 

<input type="submit" id="submit">

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
