### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/basic-sinatra-forms-lab#29]
Attribute is duplicated, please see below!

When creating your form, your "Submit" button will need to be identified by an id **attribute** attribute with value of "Submit". We're telling this to you now because our test frame work, Capybara, requires buttons to be findable by an id, title, or value attribute.

**Comment by DanielSeehausen** [comment]
thank you @arianaberger ! updated and fixed.
